"use client";

import { useState } from "react";
import { AnalysisResult } from "@/types/analysis";

function buildPrompt(problem: string, result: AnalysisResult): string {
  const lines: string[] = [];

  lines.push("# Build vs Buy Analysis");
  lines.push("");
  lines.push(`## Problem`);
  lines.push(problem);
  lines.push("");

  lines.push(`## Context`);
  lines.push(result.context_summary);
  lines.push("");

  if (result.options?.length) {
    lines.push("## Strategic Options");
    result.options.forEach(o => {
      lines.push(`### ${o.title} (${o.type})`);
      lines.push(o.tagline);
      lines.push(o.description);
      lines.push(`- Cost: ${o.estimated_cost}`);
      if (o.estimated_time) lines.push(`- Time: ${o.estimated_time}`);
      lines.push(`- Risk: ${o.risk_level}`);
      lines.push(`- Best for: ${o.best_for}`);
      if (o.pros?.length) lines.push(`- Pros: ${o.pros.join("; ")}`);
      if (o.cons?.length) lines.push(`- Cons: ${o.cons.join("; ")}`);
      lines.push("");
    });
  }

  if (result.vendor_shortlist?.length) {
    lines.push("## Vendors Evaluated");
    const sorted = [...result.vendor_shortlist].sort((a, b) => b.fit_score - a.fit_score);
    sorted.forEach(v => {
      lines.push(`- ${v.name} [${v.fit_score}/10]: ${v.verdict}`);
    });
    lines.push("");
  }

  if (result.top_build_challenges?.length) {
    lines.push("## Build Challenges");
    result.top_build_challenges.forEach(c => {
      lines.push(`### ${c.feature}`);
      lines.push(c.why_hard);
      lines.push(`- AI verdict: ${c.ai_verdict}`);
      lines.push(`- What AI can do: ${c.what_ai_can_do}`);
      lines.push(`- What AI cannot do: ${c.what_ai_cannot_do}`);
      if (c.components?.length) {
        lines.push(`- Key components: ${c.components.map(x => `${x.name} (${x.approximate_monthly_cost})`).join(", ")}`);
      }
      lines.push("");
    });
  }

  if (result.next_steps?.length) {
    lines.push("## Recommended Next Steps");
    result.next_steps.forEach(s => {
      lines.push(`- [${s.priority}] ${s.action} — ${s.rationale}`);
    });
    lines.push("");
  }

  lines.push("---");
  lines.push("Analysis generated by buyorbuild.ai");

  return lines.join("\n");
}

export default function CopyPromptButton({ result, problem }: { result: AnalysisResult; problem: string }) {
  const [copied, setCopied] = useState(false);

  function handleCopy() {
    const text = buildPrompt(problem, result);
    if (navigator.clipboard) {
      navigator.clipboard.writeText(text).then(() => {
        setCopied(true);
        setTimeout(() => setCopied(false), 2000);
      }).catch(() => {
        window.prompt("Copy this analysis:", text);
      });
    } else {
      window.prompt("Copy this analysis:", text);
    }
  }

  return (
    <button
      onClick={handleCopy}
      className="text-sm font-medium text-muted-foreground hover:text-foreground border border-border rounded-lg px-3 py-1.5 transition-colors flex items-center gap-1.5"
    >
      <svg width="13" height="13" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2.5">
        <rect x="9" y="9" width="13" height="13" rx="2" ry="2" />
        <path d="M5 15H4a2 2 0 0 1-2-2V4a2 2 0 0 1 2-2h9a2 2 0 0 1 2 2v1" />
      </svg>
      {copied ? "Copied!" : "Copy for AI"}
    </button>
  );
}
